image: 'rust:latest'

stages:
  - test
  - doc

test:
  stage: test
  script:
    - cargo test --verbose

pages:
  stage: doc
  script:
    - cargo doc --color always --no-deps --all
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; /clam-client/clam_client">' > public/index.html
  artifacts:
    paths:
      - public
  only:
    - master

cache:
  paths:
    - apt/
    - cargo/
    - target/
