image: 'rust:latest'

stages:
  - doc

pages:
  stage: doc
  script:
    - cargo doc --no-deps
    - mv target/doc public
    - echo '<meta http-equiv="refresh" content="0; url="/clam_client">' > public/index.html
  artifacts:
    paths:
      - public
  only:
    - master

cache:
  paths:
    - apt/
    - cargo/
    - target/
